photograph_new_sa:
    path:     /new
    methods: [ get ]
    defaults: { _controller: "LTPhotosBundle:Photograph:new" }

photograph_create_sa:
    path:     /create
    methods: [ post ]
    defaults: { _controller: "LTPhotosBundle:Photograph:create" }

