photograph:
    path:     /
    methods: [ get ]
    defaults: { _controller: "LTPhotosBundle:Photograph:index" }

photograph_show:
    path:     /{id}/show
    methods: [ get ]
    defaults: { _controller: "LTPhotosBundle:Photograph:show" }

photograph_new:
    path:     /new
    methods: [ get ]
    defaults: { _controller: "LTPhotosBundle:Photograph:new" }

photograph_create:
    path:     /create
    defaults: { _controller: "LTPhotosBundle:Photograph:create" }
    methods: [ POST ]

photograph_edit:
    path:     /{id}/edit
    methods: [ get ]
    defaults: { _controller: "LTPhotosBundle:Photograph:edit" }

photograph_update:
    path:     /{id}/update
    defaults: { _controller: "LTPhotosBundle:Photograph:update" }
    methods: [ POST, PUT]

photograph_delete:
    path:     /{id}/delete
    defaults: { _controller: "LTPhotosBundle:Photograph:delete" }
    methods: [ POST, DELETE ]

photograph_lock:
    path: /{id}/lock
    defaults: { _controller: "LTPhotosBundle:Photograph:lock" }
    methods: [ get ]
    requirements:
        id: \d+

photograph_unlock:
    path: /{id}/unlock
    defaults: { _controller: "LTPhotosBundle:Photograph:unlock" }
    methods: [ get ]
    requirements:
        id: \d+
