user:
    path: /
    defaults: { _controller: "LTUserBundle:User:index" }
    methods:  [ GET ]

user_create:
    path: /
    defaults: { _controller: "LTUserBundle:User:index" }
    methods:  [ POST ]

