<?php

namespace LT\PhotosBundle\Entity\SearchRepository;

use FOS\ElasticaBundle\Repository;
use LT\PhotosBundle\Model\EventSearch;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends Repository
{
    public function search(EventSearch $eventSearch) {
	if ($eventSearch->getName() != null && $eventSearch != '') {
	    $query = new \Elastica\Query\Match();
	    $query->setFieldQuery('event.name', $eventSearch->getName());
	    $query->setFieldFuzziness('event.name', 0.7);
            $query->setFieldMinimumShouldMatch('event.name', '80%');
        }
	else {
	    $query = new \Elastica\Query\Match();
	}
	$baseQuery = $query;

	$boolFilter = new \Elastica\Filter\Bool();

	if (null !== $eventSearch->getDateFrom() && null !== $eventSearch->getDateTo()) {
	    $boolFilter->addMust(new \Elastica\Filter\Range('date',
		array(
		      'gte' => \Elastica\Util::convertDate($eventSearch->getDateFrom()->getTimestamp()),
                      'lte' => \Elastica\Util::convertDate($eventSearch->getDateTo()->getTimestamp()),
		)
	    ));
	}

        $filtered = new \Elastica\Query\Filtered($baseQuery, $boolFilter);

        $query = \Elastica\Query::create($filtered);

        return $this->find($query);
    }
}
