user:
    path:     /
    defaults: { _controller: "LTUserBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "LTUserBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "LTUserBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "LTUserBundle:User:create" }
    methods: [ POST ]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "LTUserBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "LTUserBundle:User:update" }
    methods: [ POST, PUT ]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "LTUserBundle:User:delete" }
    methods: [ POST, DELETE ]

user_search:
    path: /search
    defaults: { _controller: "LTUserBundle:Ajax:userSearch" }

