lt_user_index:
    path: /user
    defaults: { _controller: "LTUserBundle:User:index" }

lt_user_search:
    path: user/search
    defaults: { _controller: "LTUserBundle:Ajax:userSearch" }

lt_user_lock:
    path: /user/lock/{id}
    defaults: { _controller: "LTUserBundle:User:lockUser" }
    requirements:
        id: \d+
