parameters:
#    lt_user.example.class: LT\UserBundle\Example
#    fos_user.model.user.class: LT\UserBundle\Entity\User

services:
#    lt_user.example:
#        class: %lt_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    lt_user_registration:
        class: LT\UserBundle\Form\Type\RegistrationFormType
        arguments: [% fos_user.model.user.class %]
        tags:
            - { name: form.type, alias: lt_user_registration }

    app.datatable.user:
        class: LT\UserBundle\Datatables\UserDatatable
        tags:
            - { name: sg.datatable.view }

